#!/bin/sh
# calyptos entry point that prepares and provisions

if [ ! -f ~/.ssh/id_rsa.pub ] ; then
  ssh-keygen -b 2048 -t rsa -N '' -f ~/.ssh/id_rsa
fi

/usr/bin/calyptos prepare --no-update-repo -p '' "$@"
/usr/bin/calyptos provision --no-update-repo -p '' "$@"
