#!/bin/sh
# Wrapper around https://eucalyptus.cloud/images image script
set -euo pipefail

eval $("/usr/sbin/clcadmin-release-credentials")
eval $("/usr/sbin/clcadmin-assume-system-credentials")
eval $("/usr/bin/euca-generate-environment-config")

TEMP_DIR="$(mktemp --directory euca-img-tmp.XXXXXXXX --tmpdir)"
function cleanup {
  umount  --recursive "${TEMP_DIR}/root" || true
  [ ! -d "${TEMP_DIR}" ] || rm -rf "${TEMP_DIR}"
}
trap cleanup EXIT

mkdir -p "${TEMP_DIR}/overlay/root/.euca"
mkdir -p "${TEMP_DIR}/overlay/eucalyptus"
mkdir "${TEMP_DIR}/workdir"
mkdir "${TEMP_DIR}/root"

curl -Ls "https://eucalyptus.cloud/images" > "${TEMP_DIR}/overlay/eucalyptus/images.py"
cat > "${TEMP_DIR}/overlay/root/.euca/admin.ini" <<EUCA_CONF
[region eucalyptus]
bootstrap-url = ${EUCA_BOOTSTRAP_URL}
ec2-url = ${EC2_URL}
s3-url = ${S3_URL}

[user admin]
key-id = ${AWS_ACCESS_KEY_ID}
secret-key = ${AWS_SECRET_ACCESS_KEY}
account-id = ${EC2_USER_ID}
EUCA_CONF

chown -R "nobody:nobody" "${TEMP_DIR}/overlay/root"
chown -R "nobody:nobody" "${TEMP_DIR}/overlay/eucalyptus"

# hide underlying euca2ools configuration files
setfattr --name="trusted.overlay.opaque" --value="y" -- "${TEMP_DIR}/overlay/root/.euca"

mount -t overlay -o "lowerdir=/,upperdir=${TEMP_DIR}/overlay,workdir=${TEMP_DIR}/workdir" overlay "${TEMP_DIR}/root"
mount -o bind "/dev" "${TEMP_DIR}/root/dev"
mount -o bind "/dev/shm" "${TEMP_DIR}/root/dev/shm"
mount -o bind "/tmp" "${TEMP_DIR}/root/tmp"

export TMPDIR="/tmp"
chroot --userspec="nobody" \
  "${TEMP_DIR}/root" \
  "/usr/bin/python2" -c "import os; import sys; os.chdir('/eucalyptus'); sys.path.insert(0,'/eucalyptus'); execfile('images.py')" "$@"

echo -e "To make image public run:\n\n\teuca-modify-image-attribute -l -a all emi-...\n"
